import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

const myFont = localFont({
    src: [
        {
            path: "./Roboto-Thin.ttf",
            weight: "100",
        },
        {
            path: "./Roboto-Regular.ttf",
            weight: "400",
        },
        {
            path: "./Roboto-Bold.ttf",
            weight: "700",
        },
    ],
    display: "swap",
    variable: "--font-roboto",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={myFont.variable}>{children}</body>
        </html>
    );
}
